Baek-Jae/1-2-3

workspace/semiPrjOmJm/WebContent/WEB-INF/views/group/groupMain.jsp
workspace/semiPrjOmJm/src/kh/semi/omjm/group/dao/GroupDao.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/service/GroupService.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/vo/GroupVo.java

GROUP 서비스 컨트롤러 DAO부분 생성

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/common/header.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/check.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/join.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/login.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/mypage.jsp
workspace/semiPrjOmJm/WebContent/css/headerStyle.css
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberCheckController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberLoginController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberLogoutController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/dao/MemberDao.java
workspace/semiPrjOmJm/src/com/kh/semi/member/service/MemberService.java

임찬선 오후 3시 커밋 / 전체적인 수정

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/check.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/join.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/login.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/mypage.jsp
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberEditController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/dao/MemberDao.java
workspace/semiPrjOmJm/src/com/kh/semi/member/service/MemberService.java
workspace/semiPrjOmJm/src/db/info.properties

info.properties > orcl 을 xe로 수정

회원가입 로그인 마이페이지 수정

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/member1.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/memberheader.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/memberstop.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/stophead.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/temp/temper.jsp
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminController.java
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminMemberStopController.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/controller/TempController.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/dao/TempDao.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/practice/tempPractice.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/service/TempService.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/vo/TempVo.java

어드민, 온도 커밋요청 / 온도계 미포함 / 구기석 커밋요청

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/rest.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/temp/temper.jsp
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminController.java
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminRestController.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/controller/TempController.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/dao/TempDao.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/service/TempService.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/vo/TempVo.java

10/25/ 기석/경로수정, jsp 경로..../커밋요청

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/join.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/mypage.jsp
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberCheckController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberMypageController.java

헤더 찜한 모임 누르면 찜한모임으로 가는 것 태원님 헤더.jsp에 부탁
마이페이지 개인정보수정 부분 화면
마이페이지 다른곳에서 > 개인정보수정누르면 check할수있게함

221026_lcs_caf1

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/restlist.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/temp/temper.jsp
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminRestController.java
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminRestListController.java
workspace/semiPrjOmJm/src/com/kh/admin/dao/AdminDao.java
workspace/semiPrjOmJm/src/com/kh/admin/dao/AdminVo.java
workspace/semiPrjOmJm/src/com/kh/admin/service/AdminService.java

관리자페이지 제제 하는중 // 리스트는 아직 미완 // 머지요청드려요//구기석

관리자페이지 제제 하는중 // 리스트는 아직 미완 // 머지요청드려요//구기석

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/join.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/likeplace.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/mypage.jsp
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberLikeplaceController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberLoginController.java

관심지역누르면 지역 선택할 수 있는 화면으로 넘어가고  + 서블릿 작업

221027 lcs home2

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/temp/temper.jsp
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminRestListController.java
workspace/semiPrjOmJm/src/com/kh/admin/dao/AdminDao.java
workspace/semiPrjOmJm/src/com/kh/admin/dao/AdminVo.java
workspace/semiPrjOmJm/src/com/kh/admin/service/AdminService.java

10/27 // 관리자 제제 리스트 수정중.....//머지요청

---

.gitignore
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/check.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/likeplace.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/login.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/mypage.jsp
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberCheckController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberLikeplaceController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberMypageController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/dao/MemberDao.java
workspace/semiPrjOmJm/src/com/kh/semi/member/service/MemberService.java
workspace/semiPrjOmJm/src/com/kh/semi/member/vo/MemberVo.java

찜한 모임 데이터 불러오기 - DB 새로 작성
마이페이지 및 로그인 화면 수정

221029 임찬선

---

.gitignore
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/check.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/likeplace.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/login.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/mypage.jsp
workspace/semiPrjOmJm/src/com/kh/semi/common/PageVo.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberCheckController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberLikeplaceController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberMypageController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/dao/MemberDao.java
workspace/semiPrjOmJm/src/com/kh/semi/member/service/MemberService.java
workspace/semiPrjOmJm/src/com/kh/semi/member/vo/MemberVo.java

221029 lcs work2

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/join.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/login.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/mypage.jsp
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberCheckController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberMypageController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/dao/MemberDao.java
workspace/semiPrjOmJm/src/com/kh/semi/member/service/MemberService.java
workspace/semiPrjOmJm/src/com/kh/semi/member/vo/MemberVo.java

221031 커밋요청합니다.

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/FAQ/list.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/notice/list.jsp
workspace/semiPrjOmJm/src/com/kh/semi/faq/dao/FaqDao.java
workspace/semiPrjOmJm/src/com/kh/semi/qna/controller/QnADeleteController.java
workspace/semiPrjOmJm/src/com/kh/semi/qna/controller/QnAEditController.java
workspace/semiPrjOmJm/src/com/kh/semi/qna/dao/QnADao.java

bje2211010910

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/group/createGroup.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/group/createOffGroup.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/group/groupMain.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/group/offGroup.jsp
workspace/semiPrjOmJm/WebContent/css/detailOffGroup.css
workspace/semiPrjOmJm/WebContent/css/groupMain.css
workspace/semiPrjOmJm/WebContent/javaScript/offGroupMain.js
workspace/semiPrjOmJm/src/kh/semi/omjm/group/controller/CreateGroupController.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/controller/CreateOffGroupController.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/controller/DetailGroupController.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/controller/DetailOffGroupController.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/controller/JoinGroupMemberController.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/controller/JoinOffGroupMemberController.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/dao/GroupDao.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/service/GroupService.java

화면
가입버튼
로그인 유저가 가입한멤버가 아니라면 생김
카테고리 새창오픈
정보받아온후 클로즈
디테일적인 화면수정중
커밋요청

커밋요청~ 몇일안남았는데 화이팅해서 마무리하고 즐건 주말 보내세요들~

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/search/category.jsp
workspace/semiPrjOmJm/WebContent/index.jsp
workspace/semiPrjOmJm/src/place/controller/LoginGroupAjaxController.java
workspace/semiPrjOmJm/src/place/controller/PlaceAjaxController.java
workspace/semiPrjOmJm/src/place/controller/SearchController.java

비로그인 : 랜덤 모임 조회 ,
검색페이지 접속 시 로그인 여부에 따른 모임 조회
검색 결과 없을 시 보여줄 모임 하는 중

1101 메인 접속 시 로그인 : 관심지역 모임 조회,

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/rest.jsp
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminRestController.java
workspace/semiPrjOmJm/src/com/kh/admin/dao/AdminDao.java
workspace/semiPrjOmJm/src/com/kh/admin/service/AdminService.java
workspace/semiPrjOmJm/src/com/kh/semi/temp/controller/PPoffTempController.java

구기석// 관리자 페이지 제제 // 제제하기....하는중 //커밋요청

구기석// 관리자 페이지 제제 // 제제하기....하는중 //커밋요청

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/mypage.jsp
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberMypageController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/dao/MemberDao.java
workspace/semiPrjOmJm/src/com/kh/semi/member/service/MemberService.java
workspace/semiPrjOmJm/src/com/kh/semi/member/vo/MemberJoinGroupVo.java

가입한 그룹 찾는 controller - service - dao 작성 및 마이페이지에 띄움 
페이징처리해야함

221101 임찬선  work3 커밋

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/common/header.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/member/mypage.jsp
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberCheckController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberMypageController.java
workspace/semiPrjOmJm/src/com/kh/semi/member/dao/MemberDao.java
workspace/semiPrjOmJm/src/com/kh/semi/member/service/MemberService.java

221102 임찬선 커밋

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/QnA/list.jsp
workspace/semiPrjOmJm/src/com/kh/semi/faq/dao/FaqDao.java
workspace/semiPrjOmJm/src/com/kh/semi/qna/controller/QnAListController.java
workspace/semiPrjOmJm/src/com/kh/semi/qna/dao/QnADao.java
workspace/semiPrjOmJm/src/com/kh/semi/qna/service/QnAService.java
workspace/semiPrjOmJm/src/com/kh/semi/qna/vo/QnAVo.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/controller/ReQnADeleteController.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/controller/ReQnAEditController.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/controller/ReQnAWriteController.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/dao/ReQnADao.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/service/ReQnAService.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/vo/ReQnAVo.java

bje 2211021558

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/FAQ/detail.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/QnA/detail.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/QnA/list.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/notice/detail.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/notice/list.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/reQnA/write.jsp
workspace/semiPrjOmJm/src/com/kh/semi/faq/dao/FaqDao.java
workspace/semiPrjOmJm/src/com/kh/semi/faq/vo/FaqVo.java
workspace/semiPrjOmJm/src/com/kh/semi/qna/controller/QnAListController.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/controller/ReQnADetailController.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/controller/ReQnAListController.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/dao/ReQnADao.java
workspace/semiPrjOmJm/src/com/kh/semi/reQnA/service/ReQnAService.java

bje2211021952

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/memberheader.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/rest.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/admin/restlist.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/temp/temper.jsp
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminController.java
workspace/semiPrjOmJm/src/com/kh/admin/controller/AdminRestController.java
workspace/semiPrjOmJm/src/com/kh/admin/dao/AdminDao.java
workspace/semiPrjOmJm/src/com/kh/admin/service/AdminService.java

관리자 로그인 // 링크 // 커밋요청 //구기석

---

workspace/semiPrjOmJm/WebContent/WEB-INF/views/group/groupMain.jsp
workspace/semiPrjOmJm/WebContent/WEB-INF/views/group/offGroup.jsp
workspace/semiPrjOmJm/src/kh/semi/omjm/group/dao/GroupDao.java
workspace/semiPrjOmJm/src/kh/semi/omjm/group/vo/OffCommentVo.java

작업아직 한참남음;;

---

workspace/semiPrjOmJm/src/com/kh/semi/member/controller/MemberLikeplaceController.java

221102 임찬선 카페 작업
